  
###########
# Travis CI configuration file
# - Enables automated testing on Travis CI web servers
# - Tests activate on push to GitHub
###########

## R CONFIGURATION 
language: r
r: bioc-release

## R PACKAGE SETTINGS
r_github_packages:
- r-lib/covr # Add the covr package to calculate code coverage for your tests

## PARALLEL OS TEST SETTINGS
# - This enables parallel testing of osx and linux on push to GitHub
matrix:
  include:
  ## LINUX SETTINGS
  - os: linux
    dist: xenial
    ## APT PACKAGE SETTINGS
    addons:
      apt:
        update: true
        packages:
          - x11proto-xf86vidmode-dev
          - tcl8.5-dev
          - tk8.5-dev
          - xvfb
    ## TESTING COMMANDS
    script:
      - R CMD build . --resave-data --compact-vignettes=gs+qpdf
      - travis_wait 30 xvfb-run R CMD check *.tar.gz # `xvfb-run` executes the command inside the xvfb virtual GUI to catch any renders
  ## OSX SETTINGS
  - os: osx
    osx_image: xcode11
    ## OSX HOMEBREW PACKAGES
    # - Dependencies for virtual GUI
    before_install:
      - brew update
      - brew cask reinstall xquartz 
      - brew install tcl-tk
      - brew link --overwrite --force tcl-tk; brew unlink tcl-tk
    ## VIRTUAL GUI
    # - Launches virtual GUI to catch renders on the headless test server
    before_script:
      - "export DISPLAY=:99.0"
      - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok ) & fi
    ## TESTING COMMANDS
    script:
      - R CMD build . --resave-data --no-build-vignettes # V
      - travis_wait 30 R CMD check *.tar.gz --no-build-vignettes # `travis_wait 30` increases the maximum time without printing to log from 10 to 30 minutes

# POST TEST COMMANDS
after_success:
- travis_wait 30 Rscript -e 'library(covr);codecov(type="all")' # Calculating code coverage


## NOTIFICATION SETTINGS
notifications:
  slack:
    rooms:
      secure: FslsSEU2U/Erx3upc42cvyU5c9EFfmMGDIWrHR13IltjJr0EeBJ/wYN51CRszVtO0QHPwiyNizrtdobHGq8rc6F0Tdr0a967Kb1Yu+sJDMpZV5zQoaeO2Vb8yitEuG6Vrcn8EnQlKGsQLWaIkk/gOK1QMYpShACQzzUqBdiOjGpkcT0l2hVV4EuViiZAv1exH7wh84dKIEw45Msss60nZZGpwj3XL/V1RtD3vufMgtF0/VCCdCqIyC0D9WdioiF3A57UhFVp0lVE/HlIG4Ji0sQlqYVzZE+caaZ2VQxPZkGBJ8R23lMH0nL7LPb7v/rB0haEAFZQSUpNYQMQRucTN8ZFp/7045BFAVTBu0Qb5CcuD0tFXNJg3dXJ/mUfOrIbh46UIOHwZnq/WjAuo95JS/mY1k7b8FkIAC+uSMUbAjWgOl6GdyhSNbbBhh2vPGtFlT8WQ0d/A4zDzhXcgTHpjSYTigVo3gis7UNngRCyIUB3ojVDi2C/JcFvNJSMjYoFZqJiNTbkBAljT9OIutUY4nWnpuZxTsbfUdmXFOQKIHqRNJ6HRwPbS5Zhu9hfelj6hdy9f78cn8Np2kNtoTTG/EaHmjhBXVHfJ5Ga9sOxJufbljIZI85HxGKVZzsmPR7319STlUsH4An+CnrzOXlV/uCztjzmwVfBBwv1ZJKRc3M=test
